sudo: required
services:
  - docker

before_install : 
  - docker build -t akilaf/docker-react-kt -f Dockerfile.dev .

script: 
  - docker run -e CI=true akilaf/docker-react-kt npm run test

deploy: 
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-654654539915"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"